apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: oc
      operation: Update
    name: ali1
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: example
    namespace: myapp
  spec:
    hard:
      pods: '4'
      requests.cpu: '1'
      requests.memory: 1Gi
      limits.cpu: '2'
      limits.memory: 2Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: mem-limit-range
    namespace: myapp
  spec:
    limits:
      - default:
          memory: 512Mi
        defaultRequest:
          memory: 256Mi
        type: Container
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
labels:
  redis: master
